--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: fichas_tecnicas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fichas_tecnicas (
    id integer NOT NULL,
    budget double precision,
    description character varying(255),
    is_paid boolean NOT NULL,
    medication character varying(255),
    paciente_id integer,
    tratamientos character varying(255)
);


ALTER TABLE public.fichas_tecnicas OWNER TO postgres;

--
-- Name: fichas_tecnicas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fichas_tecnicas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fichas_tecnicas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: odontograma; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.odontograma (
    id integer NOT NULL,
    caries_pos_x double precision,
    caries_pos_y double precision,
    manchas_pos_x double precision,
    manchas_pos_y double precision,
    paciente_id integer,
    zarro_pos_x double precision,
    zarro_pos_y double precision
);


ALTER TABLE public.odontograma OWNER TO postgres;

--
-- Name: odontograma_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.odontograma ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.odontograma_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: odontologos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.odontologos (
    id integer NOT NULL,
    apellidos character varying(255),
    "contraseña" character varying(255),
    direccion character varying(255),
    email character varying(255),
    nombre character varying(255),
    telefono character varying(255)
);


ALTER TABLE public.odontologos OWNER TO postgres;

--
-- Name: odontologos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.odontologos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.odontologos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pacientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pacientes (
    id integer NOT NULL,
    address character varying(255),
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    surname character varying(255)
);


ALTER TABLE public.pacientes OWNER TO postgres;

--
-- Name: pacientes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pacientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pacientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recepcion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recepcion (
    id integer NOT NULL,
    apellido character varying(255),
    "contraseña" character varying(255),
    direccion character varying(255),
    email character varying(255),
    nombre character varying(255),
    telefono character varying(255)
);


ALTER TABLE public.recepcion OWNER TO postgres;

--
-- Name: recepcion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recepcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recepcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fichas_tecnicas fichas_tecnicas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fichas_tecnicas
    ADD CONSTRAINT fichas_tecnicas_pkey PRIMARY KEY (id);


--
-- Name: odontograma odontograma_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.odontograma
    ADD CONSTRAINT odontograma_pkey PRIMARY KEY (id);


--
-- Name: odontologos odontologos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.odontologos
    ADD CONSTRAINT odontologos_pkey PRIMARY KEY (id);


--
-- Name: pacientes pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_pkey PRIMARY KEY (id);


--
-- Name: recepcion recepcion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recepcion
    ADD CONSTRAINT recepcion_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

